import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'


import { 
    faCircleUser, 
    faCircle, 
    faChartLine,
    faRadio,
    faRectangleList,
    faMusic,
    faPlus,
    faCirclePlay,
    faPen,
    faIcons,
    faVideo,
    faBolt,
    faCompactDisc,
    faArrowRight,
    faArrowLeft,
    faMagnifyingGlass,
    faShirt,
    faGem,
    faArrowUpFromBracket,
    faGear,
    faArrowTrendUp,
    faXmark,
    faUserLargeSlash,
    faSquareXmark,
    faSquareCheck,
    faCircleInfo,
    faPhone,
    faAd,
    faFileLines,
    faShield,
    faArrowRightFromBracket
} from '@fortawesome/free-solid-svg-icons'

export { FontAwesomeIcon }
export {
    faCircleUser,
    faCircle,
    faChartLine,
    faRadio,
    faRectangleList,
    faMusic,
    faPlus,
    faCirclePlay,
    faPen,
    faIcons,
    faVideo,
    faBolt,
    faCompactDisc,
    faArrowRight,
    faArrowLeft,
    faMagnifyingGlass,
    faShirt,
    faGem,
    faArrowUpFromBracket,
    faGear,
    faArrowTrendUp,
    faXmark,
    faUserLargeSlash,
    faSquareXmark,
    faSquareCheck,
    faCircleInfo,
    faPhone,
    faAd,
    faFileLines,
    faShield,
    faArrowRightFromBracket
}